name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
          cache-dependency-path: go.sum

      - name: Verify go.mod is tidy
        run: go mod tidy -diff

      - name: Check linter configuration
        run: make lint-config

      - name: Lint
        run: make lint

      - name: Test
        run: make test
